### ISSUE TITLE
os.cpu_count() not available

### ISSUE THREAD

**Issue by profedrini** [RecursiveForest/whatmp3#21]
Erroneously closed with "The shebang has required python3 since a8f8c50"
as this bug pertains to python 3

Issue present on Python 3.2.3 

Traceback (most recent call last): File "/home/foo/apps/bin/whatmp3", line 41, in <module> max_threads = os.cpu_count() AttributeError: 'module' object has no attribute 'cpu_count' 

Problem was introduced with 86e294b

Manually undoing that change (reimporting multiprocessing and using multiprocessing.cpu_count() makes it work.

system is : 
Linux myserver 3.16.7-ckt14-custom #2 SMP Wed Jan 27 02:14:47 CET 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by RecursiveForest** [comment]
Thanks, fixed.
