### ISSUE TITLE
os.cpu_count() not available

### ISSUE THREAD

**Issue by profedrini** [RecursiveForest/whatmp3#20]
`Traceback (most recent call last):
  File "/home/foo/apps/bin/whatmp3", line 41, in <module>
    max_threads = os.cpu_count()
AttributeError: 'module' object has no attribute 'cpu_count'
`

Problem was introduced with https://github.com/RecursiveForest/whatmp3/commit/86e294bfd7f00c374ae3e99a5e8506dcc51ba45c

Manually undoing that change (reimporting multiprocessing and using multiprocessing.cpu_count() makes it work.

system is : 
Linux myserver 3.16.7-ckt14-custom #2 SMP Wed Jan 27 02:14:47 CET 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by RecursiveForest** [comment]
The shebang has require python3 since https://github.com/RecursiveForest/whatmp3/commit/a8f8c509ea3570a5e86628b111d1cace96f7c8c7
